# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CleanADB.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 607)
        MainWindow.setMinimumSize(QtCore.QSize(753, 607))
        MainWindow.setMaximumSize(QtCore.QSize(753, 607))
        MainWindow.setStyleSheet("background-color: \"black\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 20, 361, 41))
        self.title.setStyleSheet("QLabel\n"
"{\n"
"    color: \"white\";\n"
"    font: 75 16pt \"Sans Serif\";\n"
"}")
        self.title.setObjectName("title")
        self.details = QtWidgets.QLabel(self.centralwidget)
        self.details.setGeometry(QtCore.QRect(30, 70, 361, 41))
        self.details.setStyleSheet("QLabel\n"
"{\n"
"      color: \"white\";\n"
"    font: 75 16pt \"Sans Serif\";\n"
"}")
        self.details.setObjectName("details")
        self.dev_name = QtWidgets.QLabel(self.centralwidget)
        self.dev_name.setGeometry(QtCore.QRect(30, 110, 381, 41))
        self.dev_name.setStyleSheet("QLabel\n"
"{\n"
"      color: \"white\";\n"
"    font: 75 16pt \"Sans Serif\";\n"
"}")
        self.dev_name.setObjectName("dev_name")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(30, 150, 381, 41))
        self.status.setStyleSheet("QLabel\n"
"{\n"
"      color: \"white\";\n"
"    font: 75 16pt \"Sans Serif\";\n"
"}")
        self.status.setObjectName("status")
        self.action_head = QtWidgets.QLabel(self.centralwidget)
        self.action_head.setGeometry(QtCore.QRect(30, 190, 361, 41))
        self.action_head.setStyleSheet("QLabel\n"
"{\n"
"      color: \"white\";\n"
"    font: 75 16pt \"Sans Serif\";\n"
"}")
        self.action_head.setObjectName("action_head")
        self.AppManager = QtWidgets.QPushButton(self.centralwidget)
        self.AppManager.setGeometry(QtCore.QRect(30, 240, 201, 61))
        self.AppManager.setStyleSheet("QPushButton\n"
"{\n"
"     border-radius: 10px;\n"
"     background-color: \"grey\";\n"
"     color: \"white\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}\n"
"QPushButton::hover{\n"
"     border-radius: 10px;\n"
"     background-color: rgb(229, 229, 229);\n"
"     color: \"black\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("apps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AppManager.setIcon(icon)
        self.AppManager.setIconSize(QtCore.QSize(40, 40))
        self.AppManager.setObjectName("AppManager")
        self.RecoveryReboot = QtWidgets.QPushButton(self.centralwidget)
        self.RecoveryReboot.setGeometry(QtCore.QRect(240, 240, 241, 61))
        self.RecoveryReboot.setStyleSheet("QPushButton\n"
"{\n"
"     border-radius: 10px;\n"
"     background-color: \"green\";\n"
"     color: \"white\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}\n"
"QPushButton:hover\n"
"{\n"
"     border-radius: 10px;\n"
"     background-color: \"light green\";\n"
"     color: \"black\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recovery-reboot-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecoveryReboot.setIcon(icon1)
        self.RecoveryReboot.setIconSize(QtCore.QSize(35, 35))
        self.RecoveryReboot.setObjectName("RecoveryReboot")
        self.BootloaderReboot = QtWidgets.QPushButton(self.centralwidget)
        self.BootloaderReboot.setGeometry(QtCore.QRect(490, 240, 241, 61))
        self.BootloaderReboot.setStyleSheet("QPushButton\n"
"{\n"
"     border-radius: 10px;\n"
"     background-color: \"brown\";\n"
"     color: \"white\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}\n"
"QPushButton:hover\n"
"{\n"
"     border-radius: 10px;\n"
"     background-color: \"red\";\n"
"     color: \"white\";\n"
"     font: 75 12pt \"Sans Serif\";   \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("bootloader.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BootloaderReboot.setIcon(icon2)
        self.BootloaderReboot.setIconSize(QtCore.QSize(40, 40))
        self.BootloaderReboot.setObjectName("BootloaderReboot")
        self.log = QtWidgets.QLabel(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(30, 320, 701, 201))
        self.log.setStyleSheet("QLabel{\n"
"font: 8pt \"8514oem\";\n"
"background-color: \"grey\";\n"
"color: rgb(0, 255, 127);\n"
"border-radius: 10px;\n"
"}")
        self.log.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.log.setWordWrap(True)
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInstall_ADB_Drivers = QtWidgets.QAction(MainWindow)
        self.actionInstall_ADB_Drivers.setObjectName("actionInstall_ADB_Drivers")
        self.actionCheck_for_devices = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_devices.setObjectName("actionCheck_for_devices")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionInstall_ADB_Drivers)
        self.menuMenu.addAction(self.actionCheck_for_devices)
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def refreshDevices(self):

# Execute the adb devices command and capture the output
        output = subprocess.check_output(["adb", "devices"])

# Split the output into lines and remove the first line (which contains the header)
        lines = output.decode().split("\n")[1:]

# Extract the device serial numbers from the remaining lines
        devices = [line.split("\t")[0] for line in lines if line.strip()]

# Print the list of connected devices
        print("Connected devices:")
        for device in devices:
          print(device)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "CleanADB - Version 0.1 BETA"))
        self.details.setText(_translate("MainWindow", "Details:"))
        self.dev_name.setText(_translate("MainWindow", "Device name: (Not connected)"))
        self.status.setText(_translate("MainWindow", "Status: (Not connected)"))
        self.action_head.setText(_translate("MainWindow", "Actions:"))
        self.AppManager.setText(_translate("MainWindow", "App manager"))
        self.RecoveryReboot.setText(_translate("MainWindow", "Reboot to recovery"))
        self.BootloaderReboot.setText(_translate("MainWindow", "Reboot to bootloader"))
        self.log.setText(_translate("MainWindow", " Log:"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionInstall_ADB_Drivers.setText(_translate("MainWindow", "Install ADB Drivers"))
        self.actionCheck_for_devices.setText(_translate("MainWindow", "Check for devices"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
